name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        run: |
          # Download and extract Flutter SDK
          curl -fsSL https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_2.8.1-stable.tar.xz | tar xJ
          export PATH="$PATH:`pwd`/flutter/bin"

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk
