name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '>=2.16.2 <3.0.0' # Update the Dart SDK version range

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x' # Specify the Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk
