name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.3.4' # specify the Dart SDK version

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk
